// vue-epm/src/components/layouts/CesiumMap/CesiumViewer.vue
<script setup lang="ts">
import { onMounted, onBeforeUnmount, useTemplateRef } from 'vue';
import { useCesium } from '@/composables/useCesium';

const props = withDefaults(
  defineProps<{
    mapEnabled?: boolean;
  }>(),
  {
    mapEnabled: true,
  }
);

const mapContainer = useTemplateRef('mapContainer');
const { initialize, viewer } = useCesium();

onMounted(async () => {
  if (mapContainer.value && props.mapEnabled) {
    await initialize(mapContainer.value);
    console.log('EOS Planetary Engine: Online');
  }
});

onBeforeUnmount(() => {
  if (viewer.value) {
    viewer.value.destroy();
  }
});
</script>

<template>
  <div ref="mapContainer" class="relative h-full w-full bg-black/10">
    <!-- Any HTML overlays for the globe specifically -->
    <slot></slot>
    <div v-if="!props.mapEnabled" class="absolute inset-0 flex items-center justify-center">
      Map is disabled
    </div>
  </div>
</template>

<style lang="scss" scoped></style>

// react-epm/src/components/Map/CesiumMap/CesiumViewer.tsx
import { useEffect, useRef, ReactNode } from 'react';
import { useCesium } from './CesiumContext';
//import LayerController from '@/components/Map/MapLayers/LayerController';

interface CesiumViewerProps {
  mapEnabled?: boolean;
  children?: ReactNode;
}

export default function CesiumViewer({ mapEnabled = true, children }: CesiumViewerProps) {
  const mapContainer = useRef<HTMLDivElement>(null);
  const { initialize, viewer, mapReady } = useCesium();

  useEffect(() => {
    async function init() {
      if (mapContainer.current && mapEnabled && !mapReady) {
        await initialize(mapContainer.current);
        console.log('EOS Planetary cesiumInstance: Online');
      }
    }
    init();

    return () => {
      if (viewer && !viewer.isDestroyed()) {
        viewer.destroy();
      }
    };
  }, [mapEnabled, mapReady, initialize, viewer]);

  return (
    <div
      ref={mapContainer}
      className="relative h-full w-full bg-black/10"
      id="cesium-container"
    >
      {/* Headless components that interact with the globe */}
      {/* <LayerController /> */}

      {/* Any HTML overlays for the globe specifically */}
      {children}

      {!mapEnabled && (
        <div className="absolute inset-0 z-50 flex items-center justify-center bg-black/80 text-white/50 backdrop-blur-sm">
          <span className="text-sm font-medium tracking-widest uppercase">Map is disabled</span>
        </div>
      )}
    </div>
  );
}
