// vue-epm/src/components/Map/MapLayers/LayerController.vue
<script setup lang="ts">
import { useLayerManager } from '@/components/Map/MapLayers/useLayerManager';
import { useLayers } from '@/components/Map/MapLayers/useLayers';
import { usePlanetaryEngine } from '@/components/Map/CesiumMap/keys';

const engine = usePlanetaryEngine('LayerController');

const { isLayerActive } = useLayerManager();
const { layers } = useLayers();
</script>

<template>
  <template v-if="engine.mapReady.value">
    <!-- Loop through map layers -->
    <template
      v-for="layer in layers"
      :key="layer.id"
    >
      <component
        :is="layer.component"
        v-if="isLayerActive(layer.id) && layer.component"
      />
    </template>
  </template>
</template>

// react-epm/src/components/Map/MapLayers/LayerController.tsx
import { useCesium } from '@/components/Map/CesiumMap/CesiumContext';
import { useLayerManager } from '@/components/Map/MapLayers/useLayerManager';
import { useLayers } from '@/components/Map/MapLayers/useLayers';

/**
 * Mounts map layer components when the Cesium viewer is ready and each layer is enabled.
 */
export default function LayerController() {
  const { mapReady } = useCesium();
  const { isLayerActive } = useLayerManager();
  const { layers } = useLayers();

  if (!mapReady) {
    return null;
  }

  return (
    <>
      {layers.map((layer) => {
        const Layer = layer.component;
        return isLayerActive(layer.id) && Layer ? <Layer key={layer.id} /> : null;
      })}
    </>
  );
}
