// react-epm/src/components/StatusSummary/StatTile.tsx
import React from 'react';
import { WifiIcon, InfoIcon } from 'lucide-react';
import { Skeleton } from '@/components/ui/skeleton';
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from '@/components/ui/tooltip';

import { STATUS_STYLE, type StatusKey } from '@/constants/statuses';
import { cn } from '@/lib/utils';

export interface StatTileProps {
  name: string;
  value?: string | number | Record<string, string | number>;
  tooltipText?: string;
  /** status key like 'normal' | 'warning' | 'critical' | 'info' */
  type?: StatusKey;
  component?: React.ReactNode | null;
  loading?: boolean;
  isLive?: boolean;
  /** optional text override shown instead of the mapped text */
  statusText?: string;
  /** optional color class override */
  color?: string;
  children?: React.ReactNode;
}

export const StatTile: React.FC<StatTileProps> = ({
  name,
  value,
  tooltipText,
  type = 'info',
  component = null,
  loading = false,
  isLive = false,
  statusText,
  color,
  children,
}) => {
  const displayColor = color ?? STATUS_STYLE[type];

  const sourceInfo = {
    Icon: isLive ? WifiIcon : InfoIcon,
    text: isLive ? 'Live Telemetry' : 'Simulated Data',
    className: isLive ? 'text-orbit-cyan' : 'text-white/70',
  };

  return (
    <div className="group relative flex h-full min-h-18 flex-col justify-between rounded-sm bg-black/30 p-2 shadow-[0_0_5px_0_rgb(8_47_73/0.3)]">
      {/* Status Icon */}
      <div className="absolute top-1.5 right-1.5 z-20">
        <TooltipProvider delayDuration={100}>
          <Tooltip>
            <TooltipTrigger asChild>
              <div className="cursor-help">
                <sourceInfo.Icon
                  className={cn(
                    'size-3.5 opacity-75 transition-opacity hover:opacity-100',
                    sourceInfo.className,
                    isLive && 'animate-pulse opacity-90'
                  )}
                />
              </div>
            </TooltipTrigger>
            <TooltipContent
              side="top"
              sideOffset={8}
              className="max-w-48 font-mono text-[11px] leading-tight text-white/90 shadow-2xl"
            >
              {sourceInfo.text}
            </TooltipContent>
          </Tooltip>
        </TooltipProvider>
      </div>

      {/* LABEL */}
      <span className="text-[11px] font-medium tracking-tighter text-white/40 uppercase">
        {name}
      </span>

      {/* VALUE AREA */}
      <div className="text-[12px] font-bold tracking-tight uppercase">
        {loading ? (
          <div className="flex items-center space-y-0">
            <Skeleton className="h-4 w-3/4 bg-white/10" />
          </div>
        ) : (
          <>
            {/* Custom Component Display */}
            {component || children ? (
              component || children
            ) : (
              <div className={displayColor}>{value as React.ReactNode}</div>
            )}
          </>
        )}
      </div>
    </div>
  );
};

export default StatTile;

// vue-epm/src/components/StatusSummary/StatTile.vue
<script setup lang="ts">
import { computed, type Component } from 'vue';
import { Skeleton } from '@/components/ui/skeleton';
import { WifiIcon, InfoIcon } from '@lucide/vue';

import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from '@/components/ui/tooltip';
import { STATUS_STYLE, type StatusKey } from '@/constants/statuses';
import { cn } from '@/lib/utils';

interface Props {
  name: string;
  value?: string | number | Record<string, string | number>;
  tooltipText?: string;
  /** status key like 'normal' | 'warning' | 'critical' | 'info' */
  type?: StatusKey;
  component?: Component | null;
  loading?: boolean;
  isLive?: boolean;
  /** optional text override shown instead of the mapped text */
  statusText?: string;
  /** optional color class override */
  color?: string;
}

const props = withDefaults(defineProps<Props>(), {
  value: undefined,
  tooltip: undefined,
  type: 'info',
  component: null,
  loading: false,
  isLive: false,
  statusText: undefined,
  color: undefined,
});

const displayColor = computed(() => props.color ?? STATUS_STYLE[props.type]);

// Tooltip helper
const sourceInfo = computed(() => ({
  icon: props.isLive ? WifiIcon : InfoIcon,
  text: props.isLive ? 'Live Telemetry' : 'Simulated Data',
  class: props.isLive ? 'text-orbit-cyan' : 'text-white/70',
}));
</script>

<template>
  <div
    class="group relative flex h-full min-h-18 flex-col justify-between rounded-sm bg-black/30 p-2 shadow-[0_0_5px_0_rgb(8_47_73/0.3)]"
  >
    <!-- Status Icon -->
    <div class="absolute top-1.5 right-1.5 z-20">
      <TooltipProvider :delay-duration="100">
        <Tooltip>
          <TooltipTrigger as-child>
            <div class="cursor-help">
              <component
                :is="sourceInfo.icon"
                :class="
                  cn(
                    'size-3.5 opacity-75 transition-opacity hover:opacity-100',
                    sourceInfo.class,
                    props.isLive && 'animate-pulse opacity-90'
                  )
                "
              />
            </div>
          </TooltipTrigger>
          <TooltipContent
            side="top"
            :side-offset="8"
            class="max-w-48 font-mono text-[11px] leading-tight text-white/90 shadow-2xl"
          >
            {{ sourceInfo.text }}
          </TooltipContent>
        </Tooltip>
      </TooltipProvider>
    </div>

    <!-- LABEL -->
    <span class="text-[11px] font-medium tracking-tighter text-white/40 uppercase">{{
      props.name
    }}</span>

    <!-- VALUE AREA -->
    <div class="text-[12px] font-bold tracking-tight uppercase">
      <!-- 1. LOADING STATE -->
      <div
        v-if="props.loading"
        class="flex items-center space-y-0"
      >
        <!-- We make the skeleton match our Sci-Fi theme colors -->
        <Skeleton class="h-4 w-3/4 bg-white/10" />
      </div>

      <!-- 2. DATA LOADED STATE -->
      <template v-else>
        <!-- Custom Component Display -->
        <slot v-if="props.component"></slot>

        <!-- Default Text Display -->
        <div
          v-else
          :class="displayColor"
        >
          {{ props.value }}
        </div>
      </template>
    </div>
  </div>
</template>

<style lang="scss"></style>
